databases:
  - name: group-our-transactions
    ipAllowList: []
    plan: free

services:
  - type: web
    name: group-our-transactions
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: group-our-transactions
          property: connectionString
